[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bonding_curve = "6M1WSZeEAGtc8oTkdTNWruMsW58XPByzuf6ayoN16cEq"

[programs.mainnet]
bonding_curve = "6M1WSZeEAGtc8oTkdTNWruMsW58XPByzuf6ayoN16cEq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[provider.mainnet]
url = "https://api.mainnet-beta.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
