services:
  - type: web
    name: solana-token-launchpad-api
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-url.com 